server {

    listen 80;
    server_name _;

    location / {

        root /usr/share/nginx/html;
        index index.html;

        # Autenticación básica
        auth_basic "Restricted Area";
        auth_basic_user_file /etc/nginx/auth/.htpasswd;

        try_files $uri $uri/ /index.html;

    }

}