# Inventario para despliegue del CP2
# La clave privada se obtiene desde Terraform y se guarda como private_key.pem

[web]
webserver ansible_host=158.158.44.98 ansible_user=azureuser ansible_ssh_private_key_file=private_key.pem ansible_python_interpreter=/usr/bin/python3

[registry]
localhost ansible_connection=local

[kubernetes]
localhost ansible_connection=local


[all:vars]

# Infraestructura Azure
resource_group_name=resource_group-cp2
aks_name=aks-cp2

# Container Registry
acr_name=acrmiguelferrercp2
acr_login_server=acrmiguelferrercp2.azurecr.io

# Conectividad VM
vm_public_ip=158.158.44.98

# Imágenes de contenedor
container_image_tag=cp2
web_image_name=webserver

# Aplicación AKS
app_frontend_image_name=frontend
app_backend_image_name=backend

# Namespace Kubernetes
app_namespace=cp2