---
acr_username: "acrmiguelferrercp2"
acr_password: "492pkbBmM4DE26mXrzLWNEBHLTPNrvG7Hx7Kl559OHjq6SSNM1k4JQQJ99CCACR0EKYEqg7NAAACAZCRF55w"

web_basic_auth_user: "admin"
web_basic_auth_password: "admin123"